# Site settings
title: AbaCore Capital Holdings, Inc.
email: info@abacorecapital.com
tel: 63-2-724-3759/724-5055/724-5055
fax: 63-2-724-3290
description: > # this means to ignore newlines until "baseurl:"
  AbaCore Capital Holdings, Inc.</strong> is a publicly listed holding company.
  Its shares are traded in the Philippine Stock Exchange (trading symbol:  ABA).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abacorecapital.github.io" # the base hostname & protocol for your site
twitter_username: abacorecapital
github_username:  abacorecapital

# Build settings
markdown: kramdown